import { Product } from "@/interfaces";

interface SeedProduct {
  description: string;
  images: string[];
  inStock: number;
  price: number;
  sizes: ValidSizes[];
  slug: string;
  tags: string[];
  title: string;
  type: ValidTypes;
  gender: "men" | "women" | "kid" | "unisex";
}

type ValidSizes = "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL";
type ValidTypes = "shirts" | "pants" | "hoodies" | "hats";

interface SeedData {
  products: Product[];
}

export const initialData: SeedData = {
  products: [
    {
      id: 138,
      name: "Dat Divi Engine Life Crop-top (3-Tone)",
      slug: "dat-divi-engine-life-crop-top-3-tone",
      permalink:
        "https://wp.lr.uy/producto/dat-divi-engine-life-crop-top-3-tone/",
      date_created: "2025-07-30T13:52:49",
      date_created_gmt: "2025-07-30T16:52:49",
      date_modified: "2025-07-30T13:53:39",
      date_modified_gmt: "2025-07-30T16:53:39",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This comfortable cotton crop-top features the Divi Engine logo on the front expressing how easy «data Divi Engine life» is. It is the perfect tee for any occasion.</p>\n",
      sku: "",
      price: "12.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 32,
          name: "Shirts",
          slug: "shirts-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 158,
          date_created: "2025-07-30T10:53:28",
          date_created_gmt: "2025-07-30T16:53:28",
          date_modified: "2025-07-30T10:53:28",
          date_modified_gmt: "2025-07-30T16:53:28",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Dat-Divi_Life.jpg",
          name: "Dat-Divi_Life.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi Engine"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [139, 140, 141],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount" aria-hidden="true"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;12,99</bdi></span> <span aria-hidden="true">-</span> <span class="woocommerce-Price-amount amount" aria-hidden="true"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;14,99</bdi></span><span class="screen-reader-text">Rango de precios: desde &#36;&nbsp;12,99 hasta &#36;&nbsp;14,99</span>',
      related_ids: [120, 137, 116, 133, 124],
      meta_data: [
        {
          id: 1972,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1973,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1974,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1975,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1976,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1977,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1978,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1979,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/138",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 137,
      name: "Divi Simplified Crop-top",
      slug: "divi-simplified-crop-top",
      permalink: "https://wp.lr.uy/producto/divi-simplified-crop-top/",
      date_created: "2025-07-30T13:52:48",
      date_created_gmt: "2025-07-30T16:52:48",
      date_modified: "2025-07-30T13:53:39",
      date_modified_gmt: "2025-07-30T16:53:39",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This comfortable cotton crop-top features the Divi and Divi Engine logos on the front and back. It is the perfect tee for any occasion.</p>\n",
      sku: "",
      price: "12.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 32,
          name: "Shirts",
          slug: "shirts-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 154,
          date_created: "2025-07-30T10:53:14",
          date_created_gmt: "2025-07-30T16:53:14",
          date_modified: "2025-07-30T10:53:14",
          date_modified_gmt: "2025-07-30T16:53:14",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/divi-Simplified-croptop-white.jpg",
          name: "divi-Simplified-croptop-white.jpg",
          alt: "",
        },
        {
          id: 155,
          date_created: "2025-07-30T10:53:17",
          date_created_gmt: "2025-07-30T16:53:17",
          date_modified: "2025-07-30T10:53:17",
          date_modified_gmt: "2025-07-30T16:53:17",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/divi-Simplified-croptop-blue-scaled.jpg",
          name: "divi-Simplified-croptop-blue.jpg",
          alt: "",
        },
        {
          id: 156,
          date_created: "2025-07-30T10:53:23",
          date_created_gmt: "2025-07-30T16:53:23",
          date_modified: "2025-07-30T10:53:23",
          date_modified_gmt: "2025-07-30T16:53:23",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/divi-Simplified-croptop-yellow.jpg",
          name: "divi-Simplified-croptop-yellow.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi", "Divi Engine"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
        {
          id: 2,
          name: "Color",
          slug: "pa_color",
          position: 2,
          visible: true,
          variation: true,
          options: ["Blue", "White", "Yellow"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
        {
          id: 2,
          name: "Color",
          option: "white",
        },
      ],
      variations: [142, 143, 144, 145, 146, 147, 148, 149, 157],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;12,99</bdi></span>',
      related_ids: [133, 124, 138, 116, 120],
      meta_data: [
        {
          id: 1935,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1936,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1937,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1938,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1939,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1940,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1941,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1942,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/137",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 133,
      name: "Divi Ninja Tee",
      slug: "divi-ninja-tee",
      permalink: "https://wp.lr.uy/producto/divi-ninja-tee/",
      date_created: "2025-07-30T13:52:46",
      date_created_gmt: "2025-07-30T16:52:46",
      date_modified: "2025-07-30T13:53:26",
      date_modified_gmt: "2025-07-30T16:53:26",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This comfortable cotton t-shirt features the Divi logo on the front and expresses your Ninja status with the theme. It is the perfect tee for any occasion.</p>\n",
      sku: "",
      price: "12.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: true,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 32,
          name: "Shirts",
          slug: "shirts-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 153,
          date_created: "2025-07-30T10:53:10",
          date_created_gmt: "2025-07-30T16:53:10",
          date_modified: "2025-07-30T10:53:10",
          date_modified_gmt: "2025-07-30T16:53:10",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Divi-Ninja.jpg",
          name: "Divi-Ninja.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [134, 135, 136],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;12,99</bdi></span>',
      related_ids: [120, 124, 116, 138, 137],
      meta_data: [
        {
          id: 1872,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1873,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1874,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1875,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1876,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1877,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1878,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1879,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "onbackorder",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/133",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 124,
      name: 'WooCommerce "Gimme the Money" Zipper Hoodie',
      slug: "woocommerce-gimme-the-money-zipper-hoodie",
      permalink:
        "https://wp.lr.uy/producto/woocommerce-gimme-the-money-zipper-hoodie/",
      date_created: "2025-07-30T13:52:22",
      date_created_gmt: "2025-07-30T16:52:22",
      date_modified: "2025-07-30T13:53:26",
      date_modified_gmt: "2025-07-30T16:53:26",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This WooCommerce hoodie is a must have for any WooCommerce fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your WooCommerce pride.</p>\n",
      sku: "",
      price: "27.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: true,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 31,
          name: "Hoodies",
          slug: "hoodies-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 152,
          date_created: "2025-07-30T10:53:05",
          date_created_gmt: "2025-07-30T16:53:05",
          date_modified: "2025-07-30T10:53:05",
          date_modified_gmt: "2025-07-30T16:53:05",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-Women-3.jpg",
          name: "Hoodie-Women-3.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["WooCommerce"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "medium",
        },
      ],
      variations: [125, 126, 127],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;29,99</bdi></span></del> <span class="screen-reader-text">El precio original era: &#036;&nbsp;29,99.</span><ins aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;27,99</bdi></span></ins><span class="screen-reader-text">El precio actual es: &#036;&nbsp;27,99.</span>',
      related_ids: [137, 120, 133, 138, 116],
      meta_data: [
        {
          id: 1812,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1813,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1814,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1815,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1816,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1817,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1818,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1819,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/124",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 120,
      name: "Purple Divi Engine Text Zipper Hoodie",
      slug: "purple-divi-engine-text-zipper-hoodie",
      permalink:
        "https://wp.lr.uy/producto/purple-divi-engine-text-zipper-hoodie/",
      date_created: "2025-07-30T13:52:20",
      date_created_gmt: "2025-07-30T16:52:20",
      date_modified: "2025-07-30T13:53:26",
      date_modified_gmt: "2025-07-30T16:53:26",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This Divi Engine hoodie is a must have for any Divi Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Divi Engine pride.</p>\n",
      sku: "",
      price: "27.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: true,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 31,
          name: "Hoodies",
          slug: "hoodies-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 151,
          date_created: "2025-07-30T10:53:01",
          date_created_gmt: "2025-07-30T16:53:01",
          date_modified: "2025-07-30T10:53:01",
          date_modified_gmt: "2025-07-30T16:53:01",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-Women-2.jpg",
          name: "Hoodie-Women-2.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi Engine"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "medium",
        },
      ],
      variations: [121, 122, 123],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;29,99</bdi></span></del> <span class="screen-reader-text">El precio original era: &#036;&nbsp;29,99.</span><ins aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;27,99</bdi></span></ins><span class="screen-reader-text">El precio actual es: &#036;&nbsp;27,99.</span>',
      related_ids: [138, 137, 116, 133, 124],
      meta_data: [
        {
          id: 1752,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1753,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1754,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1755,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1756,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1757,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1758,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1759,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/120",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 116,
      name: "Divi Engine Logo Zipper Hoodie",
      slug: "divi-engine-logo-zipper-hoodie",
      permalink: "https://wp.lr.uy/producto/divi-engine-logo-zipper-hoodie/",
      date_created: "2025-07-30T13:52:17",
      date_created_gmt: "2025-07-30T16:52:17",
      date_modified: "2025-07-30T13:53:25",
      date_modified_gmt: "2025-07-30T16:53:25",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This Divi Engine hoodie is a must have for any Divi Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Divi Engine pride.</p>\n",
      sku: "",
      price: "29.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 31,
          name: "Hoodies",
          slug: "hoodies-women",
        },
        {
          id: 30,
          name: "Women",
          slug: "women",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 150,
          date_created: "2025-07-30T10:52:57",
          date_created_gmt: "2025-07-30T16:52:57",
          date_modified: "2025-07-30T10:52:57",
          date_modified_gmt: "2025-07-30T16:52:57",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-Women-1.jpg",
          name: "Hoodie-Women-1.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi Engine"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "medium",
        },
      ],
      variations: [117, 118, 119],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;29,99</bdi></span>',
      related_ids: [120, 133, 138, 137, 124],
      meta_data: [
        {
          id: 1695,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1696,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1697,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1698,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1699,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1700,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1701,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1702,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/116",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 106,
      name: "Mens WordPress Hoodie",
      slug: "mens-wordpress-hoodie",
      permalink: "https://wp.lr.uy/producto/mens-wordpress-hoodie/",
      date_created: "2025-07-30T13:51:53",
      date_created_gmt: "2025-07-30T16:51:53",
      date_modified: "2025-07-30T13:53:25",
      date_modified_gmt: "2025-07-30T16:53:25",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This WordPress hoodie is a must have for any WordPress fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your WordPress pride.</p>\n",
      sku: "",
      price: "34.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 19,
          name: "Hoodies",
          slug: "hoodies",
        },
        {
          id: 17,
          name: "Men",
          slug: "men",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 132,
          date_created: "2025-07-30T10:52:40",
          date_created_gmt: "2025-07-30T16:52:40",
          date_modified: "2025-07-30T10:52:40",
          date_modified_gmt: "2025-07-30T16:52:40",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-3.jpg",
          name: "Hoodie-3.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["WordPress"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [107, 108, 115],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;34,99</bdi></span>',
      related_ids: [102, 84, 70, 88, 80],
      meta_data: [
        {
          id: 1360,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1361,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1362,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1363,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1364,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1365,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1366,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1367,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/106",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 102,
      name: "Dat Divi Engine Life Hoodie - Limited Edition",
      slug: "dat-divi-engine-life-hoodie-limited-edition",
      permalink:
        "https://wp.lr.uy/producto/dat-divi-engine-life-hoodie-limited-edition/",
      date_created: "2025-07-30T13:51:51",
      date_created_gmt: "2025-07-30T16:51:51",
      date_modified: "2025-07-30T13:52:44",
      date_modified_gmt: "2025-07-30T16:52:44",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This Divi Engine hoodie is a must have for any Divi Engine fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Divi Engine pride.</p>\n",
      sku: "",
      price: "44.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 19,
          name: "Hoodies",
          slug: "hoodies",
        },
        {
          id: 17,
          name: "Men",
          slug: "men",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 131,
          date_created: "2025-07-30T10:52:36",
          date_created_gmt: "2025-07-30T16:52:36",
          date_modified: "2025-07-30T10:52:36",
          date_modified_gmt: "2025-07-30T16:52:36",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-1.jpg",
          name: "Hoodie-1.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi Engine"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [103, 104, 105],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;44,99</bdi></span>',
      related_ids: [70, 88, 106, 80, 84],
      meta_data: [
        {
          id: 1302,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1303,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1304,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1305,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1306,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1307,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1308,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1309,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/102",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 88,
      name: "Mens Divi Hoodie",
      slug: "mens-divi-hoodie",
      permalink: "https://wp.lr.uy/producto/mens-divi-hoodie/",
      date_created: "2025-07-30T13:51:25",
      date_created_gmt: "2025-07-30T16:51:25",
      date_modified: "2025-07-30T13:52:44",
      date_modified_gmt: "2025-07-30T16:52:44",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This Divi hoodie is a must have for any Divi fan. It is made from a soft, comfortable, and durable cotton blend. The hoodie is a perfect way to stay warm and show your Divi pride.</p>\n",
      sku: "",
      price: "34.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: false,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 19,
          name: "Hoodies",
          slug: "hoodies",
        },
        {
          id: 17,
          name: "Men",
          slug: "men",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 130,
          date_created: "2025-07-30T10:52:31",
          date_created_gmt: "2025-07-30T16:52:31",
          date_modified: "2025-07-30T10:52:31",
          date_modified_gmt: "2025-07-30T16:52:31",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Hoodie-2.jpg",
          name: "Hoodie-2.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["Divi"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [89, 90, 91],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<span class="woocommerce-Price-amount amount" aria-hidden="true"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;34,99</bdi></span> <span aria-hidden="true">-</span> <span class="woocommerce-Price-amount amount" aria-hidden="true"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;39,99</bdi></span><span class="screen-reader-text">Rango de precios: desde &#36;&nbsp;34,99 hasta &#36;&nbsp;39,99</span>',
      related_ids: [106, 84, 70, 80, 102],
      meta_data: [
        {
          id: 1245,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1246,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1247,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1248,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1249,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1250,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1251,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1252,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "outofstock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/88",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
    {
      id: 84,
      name: "WordPress Tee",
      slug: "wordpress-tee",
      permalink: "https://wp.lr.uy/producto/wordpress-tee/",
      date_created: "2025-07-30T13:51:22",
      date_created_gmt: "2025-07-30T16:51:22",
      date_modified: "2025-07-30T13:52:44",
      date_modified_gmt: "2025-07-30T16:52:44",
      type: "variable",
      status: "publish",
      featured: false,
      catalog_visibility: "visible",
      description: "",
      short_description:
        "<p>This comfortable cotton t-shirt features the WordPress logo on the front and back. It is the perfect tee for any occasion.</p>\n",
      sku: "",
      price: "12.99",
      regular_price: "",
      sale_price: "",
      date_on_sale_from: null,
      date_on_sale_from_gmt: null,
      date_on_sale_to: null,
      date_on_sale_to_gmt: null,
      on_sale: true,
      purchasable: true,
      total_sales: 0,
      virtual: false,
      downloadable: false,
      downloads: [],
      download_limit: -1,
      download_expiry: -1,
      external_url: "",
      button_text: "",
      tax_status: "taxable",
      tax_class: "",
      manage_stock: false,
      stock_quantity: null,
      backorders: "no",
      backorders_allowed: false,
      backordered: false,
      low_stock_amount: null,
      sold_individually: false,
      weight: "",
      dimensions: {
        length: "",
        width: "",
        height: "",
      },
      shipping_required: true,
      shipping_taxable: true,
      shipping_class: "",
      shipping_class_id: 0,
      reviews_allowed: true,
      average_rating: "0.00",
      rating_count: 0,
      upsell_ids: [],
      cross_sell_ids: [],
      parent_id: 0,
      purchase_note: "",
      categories: [
        {
          id: 17,
          name: "Men",
          slug: "men",
        },
        {
          id: 18,
          name: "Shirts",
          slug: "shirts",
        },
      ],
      brands: [],
      tags: [],
      images: [
        {
          id: 128,
          date_created: "2025-07-30T10:52:26",
          date_created_gmt: "2025-07-30T16:52:26",
          date_modified: "2025-07-30T10:52:26",
          date_modified_gmt: "2025-07-30T16:52:26",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Shirt-1-front.jpg",
          name: "Shirt-1-front.jpg",
          alt: "",
        },
        {
          id: 129,
          date_created: "2025-07-30T10:52:28",
          date_created_gmt: "2025-07-30T16:52:28",
          date_modified: "2025-07-30T10:52:28",
          date_modified_gmt: "2025-07-30T16:52:28",
          src: "https://wp.lr.uy/wp-content/uploads/2025/07/Shirt-1-back.jpg",
          name: "Shirt-1-back.jpg",
          alt: "",
        },
      ],
      attributes: [
        {
          id: 1,
          name: "Brand",
          slug: "pa_brand",
          position: 0,
          visible: true,
          variation: false,
          options: ["WordPress"],
        },
        {
          id: 3,
          name: "Size",
          slug: "pa_size",
          position: 1,
          visible: true,
          variation: true,
          options: ["Large", "Medium", "Small"],
        },
      ],
      default_attributes: [
        {
          id: 3,
          name: "Size",
          option: "large",
        },
      ],
      variations: [85, 86, 87],
      grouped_products: [],
      menu_order: 0,
      price_html:
        '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;14,99</bdi></span></del> <span class="screen-reader-text">El precio original era: &#036;&nbsp;14,99.</span><ins aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>&nbsp;12,99</bdi></span></ins><span class="screen-reader-text">El precio actual es: &#036;&nbsp;12,99.</span>',
      related_ids: [88, 102, 80, 70, 106],
      meta_data: [
        {
          id: 1184,
          key: "_et_pb_post_hide_nav",
          value: "default",
        },
        {
          id: 1185,
          key: "_et_pb_page_layout",
          value: "et_right_sidebar",
        },
        {
          id: 1186,
          key: "_et_pb_side_nav",
          value: "off",
        },
        {
          id: 1187,
          key: "_et_pb_use_builder",
          value: "",
        },
        {
          id: 1188,
          key: "_et_pb_first_image",
          value: "",
        },
        {
          id: 1189,
          key: "_et_pb_truncate_post",
          value: "",
        },
        {
          id: 1190,
          key: "_et_pb_truncate_post_date",
          value: "",
        },
        {
          id: 1191,
          key: "_et_pb_old_content",
          value: "",
        },
      ],
      stock_status: "instock",
      has_options: true,
      post_password: "",
      global_unique_id: "",
      _links: {
        self: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products/84",
            targetHints: {
              allow: ["GET", "POST", "PUT", "PATCH", "DELETE"],
            },
          },
        ],
        collection: [
          {
            href: "https://wp.lr.uy/wp-json/wc/v3/products",
          },
        ],
      },
    },
  ],
};
